services:
  # Frontend Next.js App
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:8080"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped

  # Database Schema Initialization
  db-init:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://hakaton_user:hakaton_password@postgres:5432/hakaton_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
    command: npx prisma db push
    networks:
      - app-network
    restart: "no"

  # Backend API Server (Production)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FRONTEND_URL=http://localhost:3001
      - DATABASE_URL=postgresql://hakaton_user:hakaton_password@postgres:5432/hakaton_db
      - REDIS_URL=redis://redis:6379
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_BUCKET_NAME=chat-files
      - MINIO_PUBLIC_URL=http://localhost:9000
    command: npm start
    depends_on:
      - db-init
      - minio
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend API Server (Development)
  backend-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - FRONTEND_URL=http://localhost:3001
      - DATABASE_URL=postgresql://hakaton_user:hakaton_password@postgres:5432/hakaton_db
      - REDIS_URL=redis://redis:6379
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_BUCKET_NAME=chat-files
      - MINIO_PUBLIC_URL=http://localhost:9000
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - postgres
      - minio
    networks:
      - app-network
    restart: unless-stopped
    profiles:
      - dev

  # PostgreSQL Database
  postgres:
    image: postgis/postgis:16-3.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hakaton_db
      - POSTGRES_USER=hakaton_user
      - POSTGRES_PASSWORD=hakaton_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hakaton_user -d hakaton_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
      - MINIO_DOMAIN=localhost
      - MINIO_SERVER_URL=http://localhost:9000
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001" --address ":9000"
    networks:
      - app-network
    restart: unless-stopped

  # MinIO Client (для инициализации bucket)
  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    volumes:
      - ./minio-cors.json:/minio-cors.json
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      echo 'Setting up MinIO with FULL PUBLIC ACCESS...';
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      /usr/bin/mc mb myminio/chat-files --ignore-existing;
      
      # Make bucket completely public - anonymous access
      /usr/bin/mc anonymous set public myminio/chat-files;
      /usr/bin/mc policy set public myminio/chat-files;
      
      # Apply comprehensive CORS settings
      /usr/bin/mc admin config set myminio api cors_allow_origin '*';
      /usr/bin/mc admin config set myminio api cors_allow_methods 'GET,POST,PUT,DELETE,HEAD,OPTIONS,PATCH';
      /usr/bin/mc admin config set myminio api cors_allow_headers '*';
      /usr/bin/mc admin config set myminio api cors_allow_credentials 'true';
      /usr/bin/mc admin config set myminio api cors_max_age '86400';
      /usr/bin/mc admin config set myminio api cors_expose_headers '*';
      
      # Enable ALL anonymous operations
      /usr/bin/mc admin config set myminio api anonymous_access 'on';
      /usr/bin/mc admin config set myminio api anonymous_upload 'on';
      /usr/bin/mc admin config set myminio api anonymous_download 'on';
      /usr/bin/mc admin config set myminio api anonymous_list 'on';
      /usr/bin/mc admin config set myminio api anonymous_delete 'on';
      /usr/bin/mc admin config set myminio api anonymous_put 'on';
      /usr/bin/mc admin config set myminio api anonymous_get 'on';
      
      # Additional settings for maximum accessibility
      /usr/bin/mc admin config set myminio api allow_anonymous_bucket_creation 'on';
      /usr/bin/mc admin config set myminio api allow_anonymous_delete 'on';
      
      # Apply policy to bucket specifically
      /usr/bin/mc anonymous --recursive public my minio/chat-files;
      
      # Restart MinIO service to apply changes
      /usr/bin/mc admin service restart myminio;
      
      echo 'MinIO setup completed - BUCKET FULLY OPEN FOR PUBLIC ACCESS';
      echo 'All files in chat-files bucket are now publicly accessible without authentication';
      exit 0;
      "
    networks:
      - app-network

  # Mock Data Initializers
  mock-users:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://hakaton_user:hakaton_password@postgres:5432/hakaton_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      db-init:
        condition: service_completed_successfully
    command: node dist/scripts/create-mock-users.js
    networks:
      - app-network
    restart: "no"

  mock-contractors:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://hakaton_user:hakaton_password@postgres:5432/hakaton_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      db-init:
        condition: service_completed_successfully
    command: node dist/scripts/create-mock-contractors.js
    networks:
      - app-network
    restart: "no"

  mock-objects:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://hakaton_user:hakaton_password@postgres:5432/hakaton_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      mock-contractors:
        condition: service_completed_successfully
    command: node dist/scripts/create-mock-objects.js
    networks:
      - app-network
    restart: "no"

  seed-super-admin:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://hakaton_user:hakaton_password@postgres:5432/hakaton_db
      - REDIS_URL=redis://redis:6379
      - SUPER_ADMIN_PASSWORD=SuperAdmin123!
    depends_on:
      db-init:
        condition: service_completed_successfully
    command: node dist/scripts/seed.js
    networks:
      - app-network
    restart: "no"

  # Nginx Reverse Proxy (отключен до создания конфигурации)
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/ssl:/etc/nginx/ssl
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - app-network
  #   restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  app-network:
    driver: bridge
